# Simplified CircleCI configuration without Docker Hub authentication
# Rename this file to config.yml if you don't need Docker Hub credentials
version: 2.1

executors:
  java-executor:
    docker:
      - image: cimg/openjdk:21.0
    working_directory: ~/project
    environment:
      MAVEN_OPTS: -Xmx3200m

jobs:
  build-and-test:
    executor: java-executor
    steps:
      - checkout
      
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-
      
      - run:
          name: Build and Test
          command: mvn clean verify
      
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
      
      - run:
          name: Generate Coverage Report
          command: mvn jacoco:report
          when: always
      
      - store_test_results:
          path: target/surefire-reports
      
      - store_artifacts:
          path: target/surefire-reports
          destination: test-results
      
      - store_artifacts:
          path: target/site/jacoco
          destination: coverage-report
      
      - store_artifacts:
          path: target/*.jar
          destination: artifacts

workflows:
  version: 2
  build-test:
    jobs:
      - build-and-test

